const APP_KEY='perur-coop-demo-v1';
const seed={
 users:[{id:'ADM-001',name:'R. Karthikeyan',role:'admin',email:'admin@perurcoop.in'},{id:'WRK-1042',name:'S. Kumar',role:'worker',email:'kumar@perurcoop.in'},{id:'CUS-2201',name:'Anita Rao',role:'household',email:'anita@example.com'},{id:'INS-301',name:'Kovai Engineering College',role:'institutional',email:'procurement@kec.edu.in'}],
 workers:[{id:'WRK-1042',name:'S. Kumar',skills:['Electrician','Technician'],area:'Perur',status:'Available',rating:4.8},{id:'WRK-1178',name:'M. Selvam',skills:['Plumber','Technician'],area:'Kuniyamuthur',status:'Assigned',rating:4.7},{id:'WRK-1234',name:'P. Ravi',skills:['Carpenter'],area:'Madukkarai',status:'Available',rating:4.6},{id:'WRK-1311',name:'A. Meena',skills:['Cleaner','Domestic Helper'],area:'Coimbatore South',status:'Available',rating:4.9}],
 jobs:[{id:'JOB-2026-01842',type:'Household',customer:'Anita Rao',domain:'Electrician',location:'Perur, Coimbatore',date:'2026-09-06',time:'10:30',workers:['WRK-1042'],status:'Service Started',amount:1450,fee:50},{id:'JOB-2026-01841',type:'Institutional',customer:'Kovai Engineering College',domain:'Technician',location:'Kuniyamuthur, Coimbatore',date:'2026-09-07',time:'08:00',workers:['WRK-1178','WRK-1234'],status:'Assigned',amount:6400,fee:100},{id:'JOB-2026-01839',type:'Household',customer:'Meena Krishnan',domain:'Plumber',location:'Sundakkamuthur, Coimbatore',date:'2026-09-05',time:'15:00',workers:['WRK-1178'],status:'Completed',amount:2200,fee:50}],
 notifications:[{text:'New institutional booking requires allocation',time:'8 min ago',unread:true},{text:'Invoice INV-2026-00931 generated',time:'34 min ago',unread:true},{text:'Worker WRK-1178 started journey',time:'1 hr ago',unread:false}]
};
function state(){let x=localStorage.getItem(APP_KEY); if(!x){localStorage.setItem(APP_KEY,JSON.stringify(seed));return structuredClone(seed)} return JSON.parse(x)}
function save(x){localStorage.setItem(APP_KEY,JSON.stringify(x))}
function go(path){location.href=path}
function money(n){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)}
function configuredPlatformFee(type){let fallback=type==='Institutional'?18:10;try{let fees=JSON.parse(localStorage.getItem('perur-coop-fee-rules')||'{}');let value=Number(fees[type==='Institutional'?'institutional':'household']);return Number.isFinite(value)&&value>=0&&value<=100?value:fallback}catch(error){return fallback}}
function calculateBilling(serviceCharge,type,onsite){let serviceAmount=Number(serviceCharge);let onsiteFee=onsite==='yes'?500:0;let baseSubtotal=serviceAmount+onsiteFee;let negotiationDeduction=onsite==='yes'?-onsiteFee:0;let finalBillableAmount=baseSubtotal+negotiationDeduction;let platformFee=Math.round(finalBillableAmount*configuredPlatformFee(type)/100*100)/100;return{serviceCharge:serviceAmount,onsiteFee,baseSubtotal,negotiationDeduction,finalBillableAmount,platformFee,totalInvoice:finalBillableAmount+platformFee,workerPayout:serviceAmount}}
function billingForJob(job){if(job.onsite==='yes')return calculateBilling(job.serviceCharge??(job.billing?.serviceCharge??job.amount),job.type,job.onsite);if(job.billing)return job.billing;let serviceCharge=Number(job.serviceCharge??(Number(job.amount||0)-Number(job.fee||0)));return{serviceCharge,onsiteFee:Number(job.fee||0),baseSubtotal:serviceCharge+Number(job.fee||0),negotiationDeduction:0,finalBillableAmount:Number(job.amount||0),platformFee:0,totalInvoice:Number(job.amount||0),workerPayout:serviceCharge}}
function toast(msg){let e=document.createElement('div');e.textContent=msg;e.style.cssText='position:fixed;right:24px;bottom:24px;z-index:9999;background:#173b78;color:white;padding:14px 18px;border-radius:12px;box-shadow:0 10px 30px #0002;font:600 14px Inter,sans-serif';document.body.appendChild(e);setTimeout(()=>e.remove(),2800)}
function wireCustomerBilling(){
 const form=document.getElementById('form');
 if(form){form.addEventListener('submit',event=>{event.preventDefault();event.stopImmediatePropagation();const type=document.getElementById('type').value;const onsite=document.getElementById('onsite').value;const count=Number(document.getElementById('count').value);const serviceCharge=type==='Institutional'?count*650:1450;const billing=calculateBilling(serviceCharge,type,onsite);const current=state();const id='JOB-2026-'+String(1843+current.jobs.length).padStart(5,'0');current.jobs.unshift({id,type,customer:'Anita Rao',domain:document.getElementById('domain').value,location:onsite==='yes'?'Perur, Coimbatore':'Remote / Workshop',date:document.getElementById('date').value,time:'10:30',workers:[],status:'Pending Review',amount:billing.totalInvoice,fee:billing.onsiteFee,onsite,billing});save(current);alert('Request '+id+' submitted to the cooperative society.');go('customer.html')},true)}
 const invoiceTable=document.querySelector('h2')?.textContent.trim()==='Invoice History' ? document.querySelector('.table tbody') : null;
 if(invoiceTable){const current=state();const headers=['Invoice','Service','Date','Customer','Base Subtotal','Onsite Negotiation','Final Billable Amount','Platform Fee','Total','Status'];const headerRow=document.querySelector('.table thead tr');if(headerRow)headerRow.innerHTML=headers.map(label=>`<th>${label}</th>`).join('');invoiceTable.innerHTML=current.jobs.map(job=>{const billing=billingForJob(job);return `<tr><td><b>${job.id}</b></td><td>${job.domain}</td><td>${job.date}</td><td>${job.customer||'Anita Rao'}</td><td>${money(billing.baseSubtotal)}</td><td>${money(billing.negotiationDeduction)}</td><td>${money(billing.finalBillableAmount)}</td><td>${money(billing.platformFee)}</td><td>${money(billing.totalInvoice)}</td><td><span class="badge ${job.status==='Completed'?'green':job.status.includes('Started')?'blue':'gold'}">${job.status}</span></td></tr>`}).join('');const latest=current.jobs[0];if(latest){const billing=billingForJob(latest);const summary=document.createElement('section');summary.className='section card';summary.innerHTML=`<h2>Latest invoice calculation</h2><p class="label">Service Charge: <b>${money(billing.serviceCharge)}</b> · Onsite Fee: <b>${money(billing.onsiteFee)}</b> · Base Subtotal: <b>${money(billing.baseSubtotal)}</b> · Onsite Negotiation: <b>${money(billing.negotiationDeduction)}</b> · Final Billable Amount: <b>${money(billing.finalBillableAmount)}</b> · Platform Fee (${configuredPlatformFee(latest.type)}%): <b>${money(billing.platformFee)}</b> · Customer Total Invoice: <b>${money(billing.totalInvoice)}</b> · Worker Direct Payout: <b>${money(billing.workerPayout)} (100% Protected)</b></p>`;const settlement=document.querySelector('.section.card:last-child');settlement?.before(summary)}}
 const pendingLabel=[...document.querySelectorAll('.label')].find(el=>el.textContent.trim()==='Pending Payment');
 const pendingJob=state().jobs.find(job=>job.status!=='Completed');
 if(pendingLabel&&pendingJob){const pendingValue=pendingLabel.parentElement.querySelector('.value');if(pendingValue)pendingValue.textContent=money(billingForJob(pendingJob).totalInvoice)}
}
function wireGlobal(){
 document.querySelectorAll('a[href="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();toast('This action is available from the operational workflow.')}));
 document.querySelectorAll('button').forEach(b=>{if(!b.dataset.wired)b.addEventListener('click',()=>{const t=b.innerText.trim(); if(t && !/close|cancel/i.test(t)) toast(t+' action completed in demo mode')});b.dataset.wired='1'});
 wireCustomerBilling();
}
document.addEventListener('DOMContentLoaded',wireGlobal);
